apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb
spec:
  selector:
    matchLabels:
      app: nginx-app
  minAvailable: 2































































# apiVersion: policy/v1
# kind: PodDisruptionBudget
# metadata:
#   name: pdb
# spec:
#   minAvailable: 2
#   selector:
#     matchLabels:
#       app: nginx-app